# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(806, 597)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_status = QtGui.QWidget()
        self.tab_status.setObjectName(_fromUtf8("tab_status"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_status)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 7, 1, 3)
        self.lineEdit_card1_acoustic_speed = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_card1_acoustic_speed.setObjectName(_fromUtf8("lineEdit_card1_acoustic_speed"))
        self.gridLayout_2.addWidget(self.lineEdit_card1_acoustic_speed, 7, 1, 1, 1)
        self.pushButton_card1_acoustic_speed_test = QtGui.QPushButton(self.tab_status)
        self.pushButton_card1_acoustic_speed_test.setObjectName(_fromUtf8("pushButton_card1_acoustic_speed_test"))
        self.gridLayout_2.addWidget(self.pushButton_card1_acoustic_speed_test, 7, 3, 1, 1)
        self.lineEdit_card2_acoustic_speed = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_card2_acoustic_speed.setObjectName(_fromUtf8("lineEdit_card2_acoustic_speed"))
        self.gridLayout_2.addWidget(self.lineEdit_card2_acoustic_speed, 7, 6, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_status)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 7, 7, 1, 1)
        self.lineEdit_region1 = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_region1.setObjectName(_fromUtf8("lineEdit_region1"))
        self.gridLayout_2.addWidget(self.lineEdit_region1, 4, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_status)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton_card1_online = QtGui.QRadioButton(self.groupBox)
        self.radioButton_card1_online.setChecked(True)
        self.radioButton_card1_online.setAutoExclusive(True)
        self.radioButton_card1_online.setObjectName(_fromUtf8("radioButton_card1_online"))
        self.verticalLayout.addWidget(self.radioButton_card1_online)
        self.radioButton_card1_offline = QtGui.QRadioButton(self.groupBox)
        self.radioButton_card1_offline.setChecked(False)
        self.radioButton_card1_offline.setAutoExclusive(True)
        self.radioButton_card1_offline.setObjectName(_fromUtf8("radioButton_card1_offline"))
        self.verticalLayout.addWidget(self.radioButton_card1_offline)
        self.gridLayout_2.addWidget(self.groupBox, 2, 1, 2, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 11, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_status)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 5, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_status)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 8, 0, 1, 1)
        self.lineEdit_stream1 = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_stream1.setObjectName(_fromUtf8("lineEdit_stream1"))
        self.gridLayout_2.addWidget(self.lineEdit_stream1, 5, 1, 1, 1)
        self.lineEdit_reqion2 = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_reqion2.setObjectName(_fromUtf8("lineEdit_reqion2"))
        self.gridLayout_2.addWidget(self.lineEdit_reqion2, 4, 6, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_status)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_status)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_status)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_status)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 5, 5, 1, 1)
        self.lineEdit_card1_sensor1_location = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_card1_sensor1_location.setText(_fromUtf8(""))
        self.lineEdit_card1_sensor1_location.setObjectName(_fromUtf8("lineEdit_card1_sensor1_location"))
        self.gridLayout_2.addWidget(self.lineEdit_card1_sensor1_location, 8, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_status)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_card2_online = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_card2_online.setChecked(False)
        self.radioButton_card2_online.setObjectName(_fromUtf8("radioButton_card2_online"))
        self.verticalLayout_2.addWidget(self.radioButton_card2_online)
        self.radioButton_card2_offline = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_card2_offline.setChecked(True)
        self.radioButton_card2_offline.setAutoExclusive(True)
        self.radioButton_card2_offline.setObjectName(_fromUtf8("radioButton_card2_offline"))
        self.verticalLayout_2.addWidget(self.radioButton_card2_offline)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 6, 2, 2)
        self.lineEdit_stream2 = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_stream2.setObjectName(_fromUtf8("lineEdit_stream2"))
        self.gridLayout_2.addWidget(self.lineEdit_stream2, 5, 6, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_status)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 9, 0, 1, 1)
        self.lineEdit_card1_sensor2_location = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_card1_sensor2_location.setText(_fromUtf8(""))
        self.lineEdit_card1_sensor2_location.setObjectName(_fromUtf8("lineEdit_card1_sensor2_location"))
        self.gridLayout_2.addWidget(self.lineEdit_card1_sensor2_location, 9, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_status)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 8, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_status)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 9, 5, 1, 1)
        self.lineEdit_card2_sensor1_location = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_card2_sensor1_location.setObjectName(_fromUtf8("lineEdit_card2_sensor1_location"))
        self.gridLayout_2.addWidget(self.lineEdit_card2_sensor1_location, 8, 6, 1, 1)
        self.lineEdit_card2_sensor2_location = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_card2_sensor2_location.setObjectName(_fromUtf8("lineEdit_card2_sensor2_location"))
        self.gridLayout_2.addWidget(self.lineEdit_card2_sensor2_location, 9, 6, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_status)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 8, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_status)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 9, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_status)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 8, 7, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_status)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 9, 7, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_status)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_card1_cable_length = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_card1_cable_length.setObjectName(_fromUtf8("lineEdit_card1_cable_length"))
        self.gridLayout_2.addWidget(self.lineEdit_card1_cable_length, 6, 1, 1, 1)
        self.lineEdit_card2_cable_length = QtGui.QLineEdit(self.tab_status)
        self.lineEdit_card2_cable_length.setObjectName(_fromUtf8("lineEdit_card2_cable_length"))
        self.gridLayout_2.addWidget(self.lineEdit_card2_cable_length, 6, 6, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_status)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 6, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_status)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 6, 5, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_status)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 6, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_status)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 6, 7, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_status)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 7, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_status)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 7, 5, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_status)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 7, 2, 1, 1)
        self.pushButton_card2_acoustic_speed_test = QtGui.QPushButton(self.tab_status)
        self.pushButton_card2_acoustic_speed_test.setObjectName(_fromUtf8("pushButton_card2_acoustic_speed_test"))
        self.gridLayout_2.addWidget(self.pushButton_card2_acoustic_speed_test, 7, 8, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 2, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 7, 4, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 7, 9, 1, 1)
        self.pushButton_card1_config_ok = QtGui.QPushButton(self.tab_status)
        self.pushButton_card1_config_ok.setObjectName(_fromUtf8("pushButton_card1_config_ok"))
        self.gridLayout_2.addWidget(self.pushButton_card1_config_ok, 10, 0, 1, 1)
        self.pushButton_card2_config_ok = QtGui.QPushButton(self.tab_status)
        self.pushButton_card2_config_ok.setObjectName(_fromUtf8("pushButton_card2_config_ok"))
        self.gridLayout_2.addWidget(self.pushButton_card2_config_ok, 10, 5, 1, 1)
        self.tabWidget.addTab(self.tab_status, _fromUtf8(""))
        self.tab_card1 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_card1.sizePolicy().hasHeightForWidth())
        self.tab_card1.setSizePolicy(sizePolicy)
        self.tab_card1.setObjectName(_fromUtf8("tab_card1"))
        self.gridLayout = QtGui.QGridLayout(self.tab_card1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_figure = QtGui.QGridLayout()
        self.gridLayout_figure.setObjectName(_fromUtf8("gridLayout_figure"))
        self.GLW_spectrum = PlotWidget(self.tab_card1)
        self.GLW_spectrum.setObjectName(_fromUtf8("GLW_spectrum"))
        self.gridLayout_figure.addWidget(self.GLW_spectrum, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab_card1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_figure.addWidget(self.label, 2, 0, 1, 1)
        self.GLW_localization = PlotWidget(self.tab_card1)
        self.GLW_localization.setObjectName(_fromUtf8("GLW_localization"))
        self.gridLayout_figure.addWidget(self.GLW_localization, 1, 1, 1, 2)
        self.textEdit_record = QtGui.QTextEdit(self.tab_card1)
        self.textEdit_record.setObjectName(_fromUtf8("textEdit_record"))
        self.gridLayout_figure.addWidget(self.textEdit_record, 3, 0, 1, 3)
        self.GLW_waveform = PlotWidget(self.tab_card1)
        self.GLW_waveform.setObjectName(_fromUtf8("GLW_waveform"))
        self.gridLayout_figure.addWidget(self.GLW_waveform, 0, 0, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_figure.addItem(spacerItem5, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_figure, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_card1, _fromUtf8(""))
        self.tab_card2 = QtGui.QWidget()
        self.tab_card2.setObjectName(_fromUtf8("tab_card2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_card2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_figure_2 = QtGui.QGridLayout()
        self.gridLayout_figure_2.setObjectName(_fromUtf8("gridLayout_figure_2"))
        self.GLW_spectrum_2 = PlotWidget(self.tab_card2)
        self.GLW_spectrum_2.setObjectName(_fromUtf8("GLW_spectrum_2"))
        self.gridLayout_figure_2.addWidget(self.GLW_spectrum_2, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_figure_2.addItem(spacerItem6, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_card2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_figure_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.GLW_localization_2 = PlotWidget(self.tab_card2)
        self.GLW_localization_2.setObjectName(_fromUtf8("GLW_localization_2"))
        self.gridLayout_figure_2.addWidget(self.GLW_localization_2, 1, 1, 1, 2)
        self.textEdit_record_2 = QtGui.QTextEdit(self.tab_card2)
        self.textEdit_record_2.setObjectName(_fromUtf8("textEdit_record_2"))
        self.gridLayout_figure_2.addWidget(self.textEdit_record_2, 3, 0, 1, 3)
        self.GLW_waveform_2 = PlotWidget(self.tab_card2)
        self.GLW_waveform_2.setObjectName(_fromUtf8("GLW_waveform_2"))
        self.gridLayout_figure_2.addWidget(self.GLW_waveform_2, 0, 0, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout_figure_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_card2, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_capture = QtGui.QMenu(self.menubar)
        self.menu_capture.setObjectName(_fromUtf8("menu_capture"))
        self.menu_analysis = QtGui.QMenu(self.menubar)
        self.menu_analysis.setObjectName(_fromUtf8("menu_analysis"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_startcapture = QtGui.QAction(MainWindow)
        self.action_startcapture.setObjectName(_fromUtf8("action_startcapture"))
        self.action_paramconfig = QtGui.QAction(MainWindow)
        self.action_paramconfig.setObjectName(_fromUtf8("action_paramconfig"))
        self.action_showhis = QtGui.QAction(MainWindow)
        self.action_showhis.setObjectName(_fromUtf8("action_showhis"))
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.action_cableparam = QtGui.QAction(MainWindow)
        self.action_cableparam.setObjectName(_fromUtf8("action_cableparam"))
        self.action_stopcapture = QtGui.QAction(MainWindow)
        self.action_stopcapture.setObjectName(_fromUtf8("action_stopcapture"))
        self.menu_capture.addSeparator()
        self.menu_capture.addAction(self.action_startcapture)
        self.menu_capture.addAction(self.action_stopcapture)
        self.menu_capture.addAction(self.action_paramconfig)
        self.menu_analysis.addAction(self.action_showhis)
        self.menubar.addAction(self.menu_capture.menuAction())
        self.menubar.addAction(self.menu_analysis.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_card1_acoustic_speed_test.setText(_translate("MainWindow", "测试", None))
        self.label_24.setText(_translate("MainWindow", "m/s", None))
        self.lineEdit_region1.setText(_translate("MainWindow", "MAPUTO侧", None))
        self.radioButton_card1_online.setText(_translate("MainWindow", "在线", None))
        self.radioButton_card1_offline.setText(_translate("MainWindow", "离线", None))
        self.label_3.setText(_translate("MainWindow", "采集卡2参数", None))
        self.label_8.setText(_translate("MainWindow", "传感器1位置", None))
        self.lineEdit_stream1.setText(_translate("MainWindow", "上游", None))
        self.label_6.setText(_translate("MainWindow", "上下游", None))
        self.label_4.setText(_translate("MainWindow", "监测区域", None))
        self.label_5.setText(_translate("MainWindow", "监测区域", None))
        self.label_7.setText(_translate("MainWindow", "上下游", None))
        self.radioButton_card2_online.setText(_translate("MainWindow", "在线", None))
        self.radioButton_card2_offline.setText(_translate("MainWindow", "离线", None))
        self.label_9.setText(_translate("MainWindow", "传感器2位置", None))
        self.label_10.setText(_translate("MainWindow", "传感器1位置", None))
        self.label_11.setText(_translate("MainWindow", "传感器2位置", None))
        self.label_13.setText(_translate("MainWindow", "m", None))
        self.label_14.setText(_translate("MainWindow", "m", None))
        self.label_15.setText(_translate("MainWindow", "m", None))
        self.label_16.setText(_translate("MainWindow", "m", None))
        self.label_2.setText(_translate("MainWindow", "采集卡1参数", None))
        self.label_17.setText(_translate("MainWindow", "缆索长度", None))
        self.label_18.setText(_translate("MainWindow", "缆索长度", None))
        self.label_19.setText(_translate("MainWindow", "m", None))
        self.label_20.setText(_translate("MainWindow", "m", None))
        self.label_21.setText(_translate("MainWindow", "缆索声速", None))
        self.label_22.setText(_translate("MainWindow", "缆索声速", None))
        self.label_23.setText(_translate("MainWindow", "m/s", None))
        self.pushButton_card2_acoustic_speed_test.setText(_translate("MainWindow", "测试", None))
        self.pushButton_card1_config_ok.setText(_translate("MainWindow", "确定", None))
        self.pushButton_card2_config_ok.setText(_translate("MainWindow", "确定", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_status), _translate("MainWindow", "工作状态监测", None))
        self.label.setText(_translate("MainWindow", "记录", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_card1), _translate("MainWindow", "采集卡1监测", None))
        self.label_12.setText(_translate("MainWindow", "记录", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_card2), _translate("MainWindow", "采集卡2监测", None))
        self.menu_capture.setTitle(_translate("MainWindow", "采集设置", None))
        self.menu_analysis.setTitle(_translate("MainWindow", "分析设置", None))
        self.action_startcapture.setText(_translate("MainWindow", "开始采集", None))
        self.action_paramconfig.setText(_translate("MainWindow", "参数配置", None))
        self.action_showhis.setText(_translate("MainWindow", "查看历史", None))
        self.action_5.setText(_translate("MainWindow", "参数配置", None))
        self.action_cableparam.setText(_translate("MainWindow", "缆索参数", None))
        self.action_stopcapture.setText(_translate("MainWindow", "停止采集", None))

from pyqtgraph import PlotWidget
